salesforcecli/cli-plugins-testkit

src/hubAuth.ts
@W-8856585@ Add function to format a jwt key before saving the key data to a file.
=> fix: properly format jwtkey prior to file save

package.json
@W-8722030@
sinon should be a dependency, not a dev dependency.
=> fix: move sinon to dependencies from devDependencies

package.json, src/testSession.ts, yarn.lock
@W-8955831@
double the wait time before attempting to delete the `.sfdx` dirs to make sure analytics is done writing.
during local testing I never saw that an error was thrown, I just saw directories present after the NUTs.
Timing results
0s: directories present in the project, no error
2s: no directories, errors in CI still
4s: no directories, hopefully won't error in CI
=> fix: double wait time when deleting dirs

src/index.ts
=> fix: add missed export

.circleci/config.yml
=> chore: automerge job

src/execCmd.ts
=> fix: strip ansi from stdout and stderr

src/execCmd.ts
Adds `answers` property to `ExecCmdOptions` so that we can write NUTs for interactive commands. This feature will not work on windows
=> feat: allow option to answer prompts

src/execCmd.ts
Updates `SfExecCmdResult` to account for new json structure provided by `SfCommand`
=> feat: update SfExecCmdResult

src/testSession.ts
=> refactor: ts type assertion

.husky/commit-msg, .husky/pre-commit, .husky/pre-push, .sfdevrc.json, LICENSE.txt, package.json, yarn.lock
Bumps dev-scripts to v1
@W-10088025@
=> chore: bump dev-scripts to v1

README.md
I was getting an error with yarn add @salesforcecli/cli-plugins-testkit --dev -> needs to be salesforce instead of salesforcecli based on: https://www.npmjs.com/package/@salesforce/cli-plugins-testkit
=> Update install step

.mocharc.json, package.json, samples/generateSamplesDoc.ts, src/execCmd.ts, src/hubAuth.ts, src/testProject.ts, src/testSession.ts, src/zip.ts, test/unit/execCmd.test.ts, test/unit/testProject.test.ts, test/unit/testSession.test.ts, test/unit/zip.test.ts, test/unit/zzhubAuth.test.ts, tsconfig.json, yarn.lock
bump core, remove jsforce types
remove unused types that core fs used
bin/dev is the default
=> feat: parking orbit (core3, jsforce2)

src/execCmd.ts
fixing that timeout thing, also verifying gha migration/release
=> feat: 1 hour timeout for execCmd

src/execCmd.ts, test/unit/execCmd.test.ts
=> fix: default bin script

src/execCmd.ts, test/unit/execCmd.test.ts
=> fix: windows default executable

src/hubAuth.ts, src/testSession.ts
@W-12129945@
uses `TESTKIT_HUB_USERNAME` to get the auth url and auth with that
=> fix: auth with url when TESTKIT_HUB_USERNAME is passed

SAMPLES.md, src/execCmd.ts
=> fix: add warnings to jsonOutput type

.github/ISSUE_TEMPLATE/bug_report.md, README.md, SAMPLES.md, samples/TestSession.sample11.nut.ts, samples/TestSession.sample12.nut.ts, samples/TestSession.sample9.nut.ts, src/execCmd.ts, test/unit/execCmd.test.ts, test/unit/testSession.test.ts
@W-12607169@
removing `sfdx-cli` references
=> chore: remove sfdx references

package.json, yarn.lock
=> fix(deps): core 8

package.json, yarn.lock
[@W-19459009@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-19459009)
Reverts https://github.com/salesforcecli/cli-plugins-testkit/pull/728
Resolutions do not bubble up. This is still an issue in agents and packaging
=> W-19459009: string-width dev dep
