src/testSession.ts
test/unit/testSession.test.ts

related to and needed by @W-8721307@
sets both process.env.HOME (posix) and process.env.USERPROFILE (windows).
homedir wasn't being moved in windows
single-nut runs fine in circle
parallel nuts fail after the first one deletes the authinfo files that unfinished runs are relying on

fix: windows homedir

---

src/hubAuth.ts
src/index.ts
src/testSession.ts

Allows use to specify the auth strategy when creating a test session. If no strategy is provided, it defaults to the existing behavior (determining the strategy based on the env vars)
This is required to write NUTs for plugin-auth, where we don't want test session to do the auth'ing for us
@W-8856588@

feat: specify auth strategy

---

src/execCmd.ts

```typescript
const command = `auth:jwt:grant -d -u ${username} -i ${clientId} -f ${jwtKey} -r ${instanceUrl} --json`;
const json = execCmd<AuthFields>(command, { ensureExitCode: 0 }).jsonOutput;
```
In that example the type of `json` would be:
```typescript
{
status: number;
result: AuthFields;
}
```
@W-8856588@

feat: add type parameter to execCmd

---

src/testProject.ts
src/testSession.ts
test/unit/testProject.test.ts
test/unit/testSession.test.ts

Adds retries option to `TestSession` to allow retries on `setupCommands`
The maximum number of attempts is `1 + retries`
```typescript
return TestSession.create({
project: { gitClone: 'https://github.com/trailheadapps/dreamhouse-sfdx.git' },
setupCommands: ['sfdx force:org:create -d 1 -s -f config/project-scratch-def.json'],
retries: 2,
});
```
`TESTKIT_SETUP_RETRIES` = number of times to retry the setupCommands **after the initial attempt** before throwing an error. (This will override the retries option passed to `TestSession`)
`TESTKIT_SETUP_RETRIES_TIMEOUT` = milliseconds to wait before the next retry of setupCommands. Defaults to 5000
@W-8996075@

feat: add `retries` option

---

README.md
SAMPLES.md
samples/topics.json
src/execCmd.ts
src/hubAuth.ts
src/testProject.ts
src/testSession.ts
test/unit/execCmd.test.ts
test/unit/testProject.test.ts
test/unit/testSession.test.ts

This adds the TESTKIT_EXEC_SHELL env var which allows tests to specify a shell other than the default used by shelljs, which is the same default as child_process.  This shell will be used everywhere shelljs.exec() is called.  It will still be possible to use the env var to override the shell but use a specific one when calling `execCmd()`.
This affect:
execCmd()
TestSession setupCommands
TestProject creation with git clone or project:create
@W-8996057@

feat: add the ability to override the default shell used by shelljs.exec

---

src/hubAuth.ts
src/testSession.ts
test/unit/hubAuth.test.ts

feat: add access token hub auth strategy

---

src/hubAuth.ts
src/index.ts
src/testSession.ts
test/unit/hubAuth.test.ts

Really does not make sense to support access token auth for testkit, nuts, etc.

fix: revert access token support

---

.circleci/config.yml
test/unit/execCmd.test.ts

Use same platforms definitions as other plugins for node version selection.

chore: change circle config test-package

---

src/execCmd.ts

Include `SfdxError` properties on `SfdxExecCmdResult`

fix: include SfdxError props on SfdxExecCmdResult

---

src/execCmd.ts

Add the stdout and stderro to the error created by `getExitCodeError()`
@W-0@

fix: add both stdout and stderr to getExitCodeError

---

SAMPLES.md
samples/TestSession.sample10.nut.ts
samples/TestSession.sample11.nut.ts
samples/TestSession.sample12.nut.ts
samples/TestSession.sample9.nut.ts
src/execCmd.ts
src/hubAuth.ts
src/testSession.ts
test/unit/execCmd.test.ts
test/unit/testSession.test.ts
test/unit/zzhubAuth.test.ts

- Makes `cli` property on `execCmd` dictate which executable is used. 
- `inherit`: use `TESTKIT_EXECUTABLE_PATH` or local executable if not set
- `sfdx`: use `sfdx`
- `sf`: use `sf`
- Renames `authStrategy` to `devhubAuthStrategy` and default to `NONE`
- Adds `AUTO` option to `devhubAuthStrategy` to replace v2's existing default (determine the method by which env vars are present)
- Removes `setupCommands` from `TestSession`
- Adds `scratchOrgs` option to `TestSession` and saves `AuthFields` to `TestSession.orgs`
```typescript
const testSession = await TestSession.create({
scratchOrgs: [{ edition: 'developer', config: 'config/project-scratch-def.json', setDefault: true }],
});
// if setDefault, then the default org will be accessible with the 'default' key. Otherwise, you can use the …
```

feat!: v3 changes

---

src/testSession.ts

@W-11873398@
Wrap stdout with cann to stripAnsi

fix: strip ansi chars from stdout when authenticating the dev hub

---

src/testSession.ts
test/unit/testSession.test.ts

smarter typing for session.project
@W-12285444@

fix: session.project typing

---

src/execCmd.ts
test/unit/execCmd.test.ts

@W-12556866@
Found an instance where a plugin command finishes successfully, but needed results were capture on both stdout and stderr.
Modified execCmd to return both stdout and stderr regardless of command exit code.

fix: always return stdout and stderr from execCmd

---

src/hubAuth.ts
src/testSession.ts
test/unit/testSession.test.ts

remove some busted references to sf env commands that are now in `org` topic

fix: remove deprecated sf env commands

---

src/testSession.ts
test/unit/testSession.test.ts

scratch orgs that fail to delete (for whatever reason including commands being canceled) don't need to sit around for a week.

feat: shorter scratch org lifetime

---

.github/workflows/test.yml
SAMPLES.md
samples/TestSession.sample1.nut.ts
samples/TestSession.sample10.nut.ts
samples/TestSession.sample11.nut.ts
samples/TestSession.sample12.nut.ts
samples/TestSession.sample4.nut.ts
samples/TestSession.sample5.nut.ts
samples/TestSession.sample8.nut.ts
samples/TestSession.sample9.nut.ts
samples/execCmd.sample4.nut.ts
samples/topics.json
src/execCmd.ts
src/hubAuth.ts
src/testProject.ts
src/testSession.ts
test/unit/execCmd.test.ts
test/unit/testProject.test.ts
test/unit/testSession.test.ts
test/unit/zip.test.ts

@W-12607181@
remove `sfdx` references for `sf`

fix: move from sfdx examples/commands/defaults to sf

---

test/unit/execCmd.test.ts

JSON.parse got smarter on newer node versions.  That caused some of our assertions to fail.
I've removed the assertions that testkit shouldn't have an opinion about (assert the error type and let native JSON.parse and kit handle the message contents).  This *should* work across all node versions.
bigger picture, maybe we don't need jsonParse function and all of its fancy error constructors one 20 is the minimum.
18.15
```
> JSON.parse('{')
Uncaught SyntaxError: Unexpected end of JSON input
```
20
```
> JSON.parse('{')
Uncaught SyntaxError: Expected property name or '}' in JSON at position 1
```
https://github.com/salesforcecli/cli-plugins-testkit/actions/runs/5363099922/jobs/9730439483?pr=498

test: ut don't assert kit's responsibilities

---

src/testSession.ts

sometimes testkit session.clean fails (because file activity is still happening).  Some of the nuts have try/catch around that, which we can now remove.
There's a nodejs bug about lstat quirks on windows.  https://github.com/nodejs/node/issues/45253
I've been running this on windows to try to solve 
https://github.com/forcedotcom/sfdx-core/actions/runs/5477437565/jobs/9976954011#step:13:202
I've got it isolated, and using the debugger/debug console, it'll hang on `fs.rm` when the retry options are present, even if the timeout/max are set to a really low limit.  An EPERM just causes it to get stuck.
It's possible that on windows, logger is leaving the log file open until the worker_thread finisihes, which causes lstat problems (EPERM) during the rm retries.  We'll test that potential issue …

fix: ignore errors from when sessionDir can't be deleted

---

SAMPLES.md
samples/TestSession.sample1b.nut.ts
samples/topics.json
src/testProject.ts
src/testSession.ts
test/unit/testProject.test.ts
test/unit/testSession.test.ts

let a NUT specify the api version of their project
make the type for TestProjectOptions richer to prevent invalid combinations (previously, sourceDir and gitClone could be specified and you'd get sourceDir because that's the first thing the code checked)
[@W-13913391@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001XvsAqYAJ/view)

feat: project api version

---

src/execCmd.ts
test/unit/execCmd.test.ts

Default executable to `bin/dev.js` but fallback to `bin/dev` if it doesn't exist
@W-14125667@

feat: support bin/dev.js

---

SAMPLES.md
src/testSession.ts

allows NUTs to run ESM executables

fix: update bin/dev|run exec for when run.js exist

---

package.json
src/execCmd.ts
src/testSession.ts
test/unit/execCmd.test.ts
test/unit/testSession.test.ts

Use `bin/run.js` for executing local commands. This is a breaking change since any NUTs depending on `devPlugins` will no longer be able to use them.
[Successful test run](https://github.com/salesforcecli/plugin-limits/actions/runs/6696659435/job/18194935543)
@W-14390800@

feat!: use bin/run.js

---

src/execCmd.ts
src/testSession.ts

Cache the `process.cwd()` so that we can still resolve the path to `bin/run.js` even when `project` option is used

fix: cache process.cwd()

---

src/execCmd.ts

Add `nonZero` as an option for `ensureExitCode` to assert that the exit code was not `0`
@W-14408666@

feat: add nonZero to ensureExitCode

---

CONTRIBUTING.md
DEVELOPING.md
LICENSE.txt
README.md
src/execCmd.ts

there's unicode characters in the updated inquirer lists that were keeping the NUT automation from finding the expected values 
side-quest during @W-14795554@, which requires this change
an example from debug (note where the `"` ends up on the 2nd line 
```
testkit:execInteractiveCmd should scroll for answer: "hello world" +0ms
testkit:exe" +0msactiveCmd selected: "hello world
```

fix: regex for new inquirer select

---

package.json
src/execCmd.ts

execInteractiveCmd has a problem with spaces (it does split on ' ') but that also hits the spaces inside double quotes in flag values like `--flag "space here"`
This provides the alternative to pass in the normal "argv" structure like execInteractiveCmd(['mycmd', '--flag', '"space here"']) 
also cleaned up some param-reassign linter stuff in execCmd module
used here (proof of correctness) https://github.com/salesforcecli/plugin-deploy-retrieve/pull/988

feat: execInteractive takes string or string[]

---

package.json
test/unit/testSession.test.ts
yarn.lock

We had test failures in [forcedotcom/agents](https://github.com/forcedotcom/agents/pull/149) and [forcedotcom/packaging](https://github.com/forcedotcom/packaging/pull/771) due to a dependency change with a major version of `string-width`
```
$HOME/dev/agents/node_modules/mocha/node_modules/yargs/build/index.cjs:1040
width = Math.max(shim.stringWidth(modifier ? `${modifier} ${getText(v[0])}` : getText(v[0])) + getIndentation(v[0]), width);
^
TypeError: shim.stringWidth is not a function
```
This was a web of dependencies, this is what I could gather...
- `@salesforce/cli-plugins-testkit@5.3.39` bumped `@types/shelljs@0.8.17`
- This brought in `glob@11.0.3` → `jackspeak@4.1.1` → `@isaacs/cliui@8.0.2` → `string-width@5.1.2` (ESM)
- **`yargs`** expected CommonJS `string-width@4.x` (CJS) but …

W-19459009: string-width resolution
